// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteComment(ctx context.Context, id int64) error
	DeleteTicket(ctx context.Context, id int64) error
	GetComment(ctx context.Context, id int64) (Comment, error)
	GetTicket(ctx context.Context, id int64) (Ticket, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListAllTickets(ctx context.Context, arg ListAllTicketsParams) ([]Ticket, error)
	ListComment(ctx context.Context, arg ListCommentParams) ([]Comment, error)
	ListTickets(ctx context.Context, arg ListTicketsParams) ([]Ticket, error)
	ListTicketsAssigned(ctx context.Context, arg ListTicketsAssignedParams) ([]Ticket, error)
}

var _ Querier = (*Queries)(nil)
