// Code generated by tools/generate_ticket_state_contract.py; DO NOT EDIT.

package domain

const (
	TicketStateOpen       TicketState = 1
	TicketStatePending    TicketState = 2
	TicketStateInProgress TicketState = 3
	TicketStateResolved   TicketState = 4
	TicketStateClosed     TicketState = 5
	TicketStateCancelled  TicketState = 6
)

var ticketStateWireValues = map[TicketState]string{
	TicketStateOpen:       "open",
	TicketStatePending:    "pending",
	TicketStateInProgress: "in_progress",
	TicketStateResolved:   "resolved",
	TicketStateClosed:     "closed",
	TicketStateCancelled:  "cancelled",
}

var ticketStateByInput = map[string]TicketState{
	"open":        TicketStateOpen,
	"pending":     TicketStatePending,
	"in_progress": TicketStateInProgress,
	"in progress": TicketStateInProgress,
	"resolved":    TicketStateResolved,
	"closed":      TicketStateClosed,
	"cancelled":   TicketStateCancelled,
	"cancel":      TicketStateCancelled,
}

var allowedTransitions = map[TicketState][]TicketState{
	TicketStateOpen:       {TicketStatePending, TicketStateInProgress, TicketStateCancelled},
	TicketStatePending:    {TicketStateOpen, TicketStateInProgress, TicketStateResolved, TicketStateCancelled},
	TicketStateInProgress: {TicketStateResolved},
	TicketStateResolved:   {TicketStateOpen, TicketStatePending, TicketStateClosed, TicketStateCancelled},
	TicketStateClosed:     {},
	TicketStateCancelled:  {},
}

var ticketStateOrder = []TicketState{TicketStateOpen, TicketStatePending, TicketStateInProgress, TicketStateResolved, TicketStateClosed, TicketStateCancelled}
