// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comment.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (description, ticket_id, created_by ) VALUES ($1, $2, $3) RETURNING id, ticket_id, created_by, description, created_at, updated_at
`

type CreateCommentParams struct {
	Description string    `json:"description"`
	TicketID    int64     `json:"ticket_id"`
	CreatedBy   uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, createComment, arg.Description, arg.TicketID, arg.CreatedBy)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.CreatedBy,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments WHERE id = $1
`

func (q *Queries) DeleteComment(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteComment, id)
	return err
}

const getComment = `-- name: GetComment :one
SELECT id, ticket_id, created_by, description, created_at, updated_at FROM comments WHERE id = $1 LIMIT 1
`

func (q *Queries) GetComment(ctx context.Context, id int64) (Comment, error) {
	row := q.db.QueryRowContext(ctx, getComment, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.CreatedBy,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listComment = `-- name: ListComment :many
SELECT id, ticket_id, created_by, description, created_at, updated_at FROM comments WHERE ticket_id=$1 ORDER BY id LIMIT $2 OFFSET $3
`

type ListCommentParams struct {
	TicketID int64 `json:"ticket_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

func (q *Queries) ListComment(ctx context.Context, arg ListCommentParams) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, listComment, arg.TicketID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.CreatedBy,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
