// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Comment struct {
	CreatedBy   uuid.UUID     `json:"created_by"`
	Description string        `json:"description"`
	CreatedAt   time.Time     `json:"created_at"`
	UpdatedAt   sql.NullTime  `json:"updated_at"`
	ID          uuid.NullUUID `json:"id"`
	TicketID    uuid.NullUUID `json:"ticket_id"`
}

type Ticket struct {
	CreatedBy   uuid.UUID     `json:"created_by"`
	AssignedTo  uuid.NullUUID `json:"assigned_to"`
	Title       string        `json:"title"`
	Description string        `json:"description"`
	State       int32         `json:"state"`
	Priority    int32         `json:"priority"`
	CreatedAt   time.Time     `json:"created_at"`
	UpdatedAt   sql.NullTime  `json:"updated_at"`
	ID          uuid.NullUUID `json:"id"`
}

type User struct {
	ID             uuid.UUID      `json:"id"`
	HashedPassword string         `json:"hashed_password"`
	FirstName      string         `json:"first_name"`
	LastName       string         `json:"last_name"`
	Email          string         `json:"email"`
	Role           sql.NullString `json:"role"`
	UpdatedAt      time.Time      `json:"updated_at"`
	CreatedAt      time.Time      `json:"created_at"`
}
