// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteComment(ctx context.Context, id uuid.NullUUID) error
	DeleteTicket(ctx context.Context, id uuid.NullUUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetAllUsers(ctx context.Context) ([]GetAllUsersRow, error)
	GetComment(ctx context.Context, id uuid.NullUUID) (Comment, error)
	GetTicket(ctx context.Context, id uuid.NullUUID) (Ticket, error)
	GetTicketsByAssignee(ctx context.Context, assignedTo uuid.NullUUID) ([]Ticket, error)
	GetTicketsByCreator(ctx context.Context, createdBy uuid.UUID) ([]Ticket, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListAllTickets(ctx context.Context, arg ListAllTicketsParams) ([]Ticket, error)
	ListComment(ctx context.Context, arg ListCommentParams) ([]Comment, error)
	ListTickets(ctx context.Context, arg ListTicketsParams) ([]Ticket, error)
	ListTicketsAssigned(ctx context.Context, arg ListTicketsAssignedParams) ([]Ticket, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateTicket(ctx context.Context, arg UpdateTicketParams) (Ticket, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
