// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteComment(ctx context.Context, id uuid.UUID) error
	DeleteTicket(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetActiveTickets(ctx context.Context) ([]Ticket, error)
	GetAllAgents(ctx context.Context) ([]User, error)
	GetAllUsers(ctx context.Context) ([]GetAllUsersRow, error)
	GetComment(ctx context.Context, id uuid.UUID) (Comment, error)
	GetTicket(ctx context.Context, id uuid.UUID) (Ticket, error)
	GetTicketByNumber(ctx context.Context, ticketNumber int64) (Ticket, error)
	GetTicketsByAssignee(ctx context.Context, dollar_1 []uuid.UUID) ([]Ticket, error)
	GetTicketsByCreator(ctx context.Context, createdBy uuid.UUID) ([]Ticket, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListAllTickets(ctx context.Context, arg ListAllTicketsParams) ([]Ticket, error)
	// Optional filters: pass NULL for any sqlc.narg to skip that condition.
	// filter_assignee: tickets where assigned_to contains this user id.
	ListAllTicketsByStatePriority(ctx context.Context, arg ListAllTicketsByStatePriorityParams) ([]Ticket, error)
	ListComment(ctx context.Context, arg ListCommentParams) ([]Comment, error)
	ListTickets(ctx context.Context, arg ListTicketsParams) ([]Ticket, error)
	ListTicketsAssigned(ctx context.Context, arg ListTicketsAssignedParams) ([]Ticket, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateTicket(ctx context.Context, arg UpdateTicketParams) (Ticket, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
