// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ticket.sql

package db

import (
	"context"
	"database/sql"
)

const createTicket = `-- name: CreateTicket :one
INSERT INTO tickets (title, description, created_by ) VALUES ($1, $2, $3) RETURNING id, created_by, assigned_to, title, description, state, priority, created_at, updated_at
`

type CreateTicketParams struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	CreatedBy   string `json:"created_by"`
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, createTicket, arg.Title, arg.Description, arg.CreatedBy)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.AssignedTo,
		&i.Title,
		&i.Description,
		&i.State,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTicket = `-- name: DeleteTicket :exec
DELETE FROM tickets WHERE id = $1
`

func (q *Queries) DeleteTicket(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTicket, id)
	return err
}

const getTicket = `-- name: GetTicket :one
SELECT id, created_by, assigned_to, title, description, state, priority, created_at, updated_at FROM tickets WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTicket(ctx context.Context, id int64) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, getTicket, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.AssignedTo,
		&i.Title,
		&i.Description,
		&i.State,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTicketsByAssignee = `-- name: GetTicketsByAssignee :many
SELECT id, created_by, assigned_to, title, description, state, priority, created_at, updated_at FROM tickets
WHERE assigned_to = $1
ORDER BY created_at DESC
`

func (q *Queries) GetTicketsByAssignee(ctx context.Context, assignedTo sql.NullString) ([]Ticket, error) {
	rows, err := q.db.QueryContext(ctx, getTicketsByAssignee, assignedTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.CreatedBy,
			&i.AssignedTo,
			&i.Title,
			&i.Description,
			&i.State,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTicketsByCreator = `-- name: GetTicketsByCreator :many
SELECT id, created_by, assigned_to, title, description, state, priority, created_at, updated_at FROM tickets
WHERE created_by = $1
ORDER BY created_at DESC
`

func (q *Queries) GetTicketsByCreator(ctx context.Context, createdBy string) ([]Ticket, error) {
	rows, err := q.db.QueryContext(ctx, getTicketsByCreator, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.CreatedBy,
			&i.AssignedTo,
			&i.Title,
			&i.Description,
			&i.State,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllTickets = `-- name: ListAllTickets :many
SELECT id, created_by, assigned_to, title, description, state, priority, created_at, updated_at FROM tickets ORDER BY id LIMIT $1 OFFSET $2
`

type ListAllTicketsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAllTickets(ctx context.Context, arg ListAllTicketsParams) ([]Ticket, error) {
	rows, err := q.db.QueryContext(ctx, listAllTickets, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.CreatedBy,
			&i.AssignedTo,
			&i.Title,
			&i.Description,
			&i.State,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTickets = `-- name: ListTickets :many
SELECT id, created_by, assigned_to, title, description, state, priority, created_at, updated_at FROM tickets WHERE created_by=$1 ORDER BY id LIMIT $2 OFFSET $3
`

type ListTicketsParams struct {
	CreatedBy string `json:"created_by"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

func (q *Queries) ListTickets(ctx context.Context, arg ListTicketsParams) ([]Ticket, error) {
	rows, err := q.db.QueryContext(ctx, listTickets, arg.CreatedBy, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.CreatedBy,
			&i.AssignedTo,
			&i.Title,
			&i.Description,
			&i.State,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsAssigned = `-- name: ListTicketsAssigned :many
SELECT id, created_by, assigned_to, title, description, state, priority, created_at, updated_at FROM tickets WHERE assigned_to=$1 ORDER BY id LIMIT $2 OFFSET $3
`

type ListTicketsAssignedParams struct {
	AssignedTo sql.NullString `json:"assigned_to"`
	Limit      int32          `json:"limit"`
	Offset     int32          `json:"offset"`
}

func (q *Queries) ListTicketsAssigned(ctx context.Context, arg ListTicketsAssignedParams) ([]Ticket, error) {
	rows, err := q.db.QueryContext(ctx, listTicketsAssigned, arg.AssignedTo, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.CreatedBy,
			&i.AssignedTo,
			&i.Title,
			&i.Description,
			&i.State,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTicket = `-- name: UpdateTicket :one
UPDATE tickets
SET 
    title = $2,
    description = $3,
    state = $4,
    priority = $5,
    assigned_to = $6,
    updated_at = $7
WHERE id = $1
RETURNING id, created_by, assigned_to, title, description, state, priority, created_at, updated_at
`

type UpdateTicketParams struct {
	ID          int64          `json:"id"`
	Title       string         `json:"title"`
	Description string         `json:"description"`
	State       int32          `json:"state"`
	Priority    int32          `json:"priority"`
	AssignedTo  sql.NullString `json:"assigned_to"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

func (q *Queries) UpdateTicket(ctx context.Context, arg UpdateTicketParams) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, updateTicket,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.State,
		arg.Priority,
		arg.AssignedTo,
		arg.UpdatedAt,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.AssignedTo,
		&i.Title,
		&i.Description,
		&i.State,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
