// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountTicketStatsAll(ctx context.Context, dollar_1 []uuid.UUID) (CountTicketStatsAllRow, error)
	CountTicketStatsByAssignee(ctx context.Context, arg CountTicketStatsByAssigneeParams) (CountTicketStatsByAssigneeRow, error)
	CountTicketStatsByCreator(ctx context.Context, arg CountTicketStatsByCreatorParams) (CountTicketStatsByCreatorRow, error)
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// JIT provisioning: first sign-in of a Keycloak subject with no local row.
	CreateUserFromKeycloak(ctx context.Context, arg CreateUserFromKeycloakParams) (User, error)
	DeleteComment(ctx context.Context, id uuid.UUID) error
	DeleteTicket(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetActiveTickets(ctx context.Context) ([]Ticket, error)
	GetAllAgents(ctx context.Context) ([]User, error)
	GetAllUsers(ctx context.Context) ([]GetAllUsersRow, error)
	GetAutoAssignmentCandidates(ctx context.Context, arg GetAutoAssignmentCandidatesParams) ([]GetAutoAssignmentCandidatesRow, error)
	GetComment(ctx context.Context, id uuid.UUID) (Comment, error)
	GetTicket(ctx context.Context, id uuid.UUID) (Ticket, error)
	GetTicketByNumber(ctx context.Context, ticketNumber int64) (Ticket, error)
	GetTicketsByAssignee(ctx context.Context, dollar_1 []uuid.UUID) ([]Ticket, error)
	GetTicketsByCreator(ctx context.Context, createdBy uuid.UUID) ([]Ticket, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByKeycloakID(ctx context.Context, keycloakID uuid.NullUUID) (User, error)
	GetUsersByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]User, error)
	// Claims a pre-existing row (matched by email) for a Keycloak subject, and
	// refreshes the profile/role from the token. The keycloak_id IS NULL guard makes
	// this a no-op if the row was already linked to a different subject, so a second
	// Keycloak account with the same email can never steal an existing identity.
	LinkUserToKeycloak(ctx context.Context, arg LinkUserToKeycloakParams) (User, error)
	ListAllTickets(ctx context.Context, arg ListAllTicketsParams) ([]Ticket, error)
	// Optional filters: pass NULL for any sqlc.narg to skip that condition.
	// filter_assignee: tickets where assigned_to contains this user id.
	ListAllTicketsByStatePriority(ctx context.Context, arg ListAllTicketsByStatePriorityParams) ([]Ticket, error)
	ListComment(ctx context.Context, arg ListCommentParams) ([]Comment, error)
	ListTickets(ctx context.Context, arg ListTicketsParams) ([]Ticket, error)
	ListTicketsAssigned(ctx context.Context, arg ListTicketsAssignedParams) ([]Ticket, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	// Refreshes a linked row when the token's profile or role has drifted from it.
	SyncUserFromKeycloak(ctx context.Context, arg SyncUserFromKeycloakParams) (User, error)
	UpdateTicket(ctx context.Context, arg UpdateTicketParams) (Ticket, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
