// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ticket.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const countTicketStatsAll = `-- name: CountTicketStatsAll :one
SELECT
  COUNT(*)::int4 AS total,
  COUNT(*) FILTER (WHERE state = 1)::int4 AS open,
  COUNT(*) FILTER (WHERE state = 2)::int4 AS pending,
  COUNT(*) FILTER (WHERE state = 4)::int4 AS resolved,
  COUNT(*) FILTER (WHERE assigned_to @> $1::uuid[])::int4 AS mine
FROM tickets
`

type CountTicketStatsAllRow struct {
	Total    int32 `json:"total"`
	Open     int32 `json:"open"`
	Pending  int32 `json:"pending"`
	Resolved int32 `json:"resolved"`
	Mine     int32 `json:"mine"`
}

func (q *Queries) CountTicketStatsAll(ctx context.Context, dollar_1 []uuid.UUID) (CountTicketStatsAllRow, error) {
	row := q.db.QueryRowContext(ctx, countTicketStatsAll, pq.Array(dollar_1))
	var i CountTicketStatsAllRow
	err := row.Scan(
		&i.Total,
		&i.Open,
		&i.Pending,
		&i.Resolved,
		&i.Mine,
	)
	return i, err
}

const countTicketStatsByAssignee = `-- name: CountTicketStatsByAssignee :one
SELECT
  COUNT(*)::int4 AS total,
  COUNT(*) FILTER (WHERE state = 1)::int4 AS open,
  COUNT(*) FILTER (WHERE state = 2)::int4 AS pending,
  COUNT(*) FILTER (WHERE state = 4)::int4 AS resolved,
  COUNT(*) FILTER (WHERE assigned_to @> $2::uuid[])::int4 AS mine
FROM tickets
WHERE assigned_to @> $1::uuid[]
`

type CountTicketStatsByAssigneeParams struct {
	Column1 []uuid.UUID `json:"column_1"`
	Column2 []uuid.UUID `json:"column_2"`
}

type CountTicketStatsByAssigneeRow struct {
	Total    int32 `json:"total"`
	Open     int32 `json:"open"`
	Pending  int32 `json:"pending"`
	Resolved int32 `json:"resolved"`
	Mine     int32 `json:"mine"`
}

func (q *Queries) CountTicketStatsByAssignee(ctx context.Context, arg CountTicketStatsByAssigneeParams) (CountTicketStatsByAssigneeRow, error) {
	row := q.db.QueryRowContext(ctx, countTicketStatsByAssignee, pq.Array(arg.Column1), pq.Array(arg.Column2))
	var i CountTicketStatsByAssigneeRow
	err := row.Scan(
		&i.Total,
		&i.Open,
		&i.Pending,
		&i.Resolved,
		&i.Mine,
	)
	return i, err
}

const countTicketStatsByCreator = `-- name: CountTicketStatsByCreator :one
SELECT
  COUNT(*)::int4 AS total,
  COUNT(*) FILTER (WHERE state = 1)::int4 AS open,
  COUNT(*) FILTER (WHERE state = 2)::int4 AS pending,
  COUNT(*) FILTER (WHERE state = 4)::int4 AS resolved,
  COUNT(*) FILTER (WHERE assigned_to @> $2::uuid[])::int4 AS mine
FROM tickets
WHERE created_by = $1
`

type CountTicketStatsByCreatorParams struct {
	CreatedBy uuid.UUID   `json:"created_by"`
	Column2   []uuid.UUID `json:"column_2"`
}

type CountTicketStatsByCreatorRow struct {
	Total    int32 `json:"total"`
	Open     int32 `json:"open"`
	Pending  int32 `json:"pending"`
	Resolved int32 `json:"resolved"`
	Mine     int32 `json:"mine"`
}

func (q *Queries) CountTicketStatsByCreator(ctx context.Context, arg CountTicketStatsByCreatorParams) (CountTicketStatsByCreatorRow, error) {
	row := q.db.QueryRowContext(ctx, countTicketStatsByCreator, arg.CreatedBy, pq.Array(arg.Column2))
	var i CountTicketStatsByCreatorRow
	err := row.Scan(
		&i.Total,
		&i.Open,
		&i.Pending,
		&i.Resolved,
		&i.Mine,
	)
	return i, err
}

const createTicket = `-- name: CreateTicket :one
INSERT INTO tickets (title, description, created_by, updated_at, skills, priority) VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, created_by, assigned_to, title, description, state, priority, created_at, updated_at, ticket_number, skills
`

type CreateTicketParams struct {
	Title       string    `json:"title"`
	Description string    `json:"description"`
	CreatedBy   uuid.UUID `json:"created_by"`
	UpdatedAt   time.Time `json:"updated_at"`
	Skills      []string  `json:"skills"`
	Priority    int32     `json:"priority"`
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, createTicket,
		arg.Title,
		arg.Description,
		arg.CreatedBy,
		arg.UpdatedAt,
		pq.Array(arg.Skills),
		arg.Priority,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		pq.Array(&i.AssignedTo),
		&i.Title,
		&i.Description,
		&i.State,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TicketNumber,
		pq.Array(&i.Skills),
	)
	return i, err
}

const deleteTicket = `-- name: DeleteTicket :exec
DELETE FROM tickets WHERE id = $1
`

func (q *Queries) DeleteTicket(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTicket, id)
	return err
}

const getActiveTickets = `-- name: GetActiveTickets :many
SELECT id, created_by, assigned_to, title, description, state, priority, created_at, updated_at, ticket_number, skills FROM tickets
WHERE state IN (1, 2)
ORDER BY created_at
`

func (q *Queries) GetActiveTickets(ctx context.Context) ([]Ticket, error) {
	rows, err := q.db.QueryContext(ctx, getActiveTickets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.CreatedBy,
			pq.Array(&i.AssignedTo),
			&i.Title,
			&i.Description,
			&i.State,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TicketNumber,
			pq.Array(&i.Skills),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTicket = `-- name: GetTicket :one
SELECT id, created_by, assigned_to, title, description, state, priority, created_at, updated_at, ticket_number, skills FROM tickets WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTicket(ctx context.Context, id uuid.UUID) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, getTicket, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		pq.Array(&i.AssignedTo),
		&i.Title,
		&i.Description,
		&i.State,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TicketNumber,
		pq.Array(&i.Skills),
	)
	return i, err
}

const getTicketByNumber = `-- name: GetTicketByNumber :one
SELECT id, created_by, assigned_to, title, description, state, priority, created_at, updated_at, ticket_number, skills FROM tickets WHERE ticket_number = $1 LIMIT 1
`

func (q *Queries) GetTicketByNumber(ctx context.Context, ticketNumber int64) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, getTicketByNumber, ticketNumber)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		pq.Array(&i.AssignedTo),
		&i.Title,
		&i.Description,
		&i.State,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TicketNumber,
		pq.Array(&i.Skills),
	)
	return i, err
}

const getTicketsByAssignee = `-- name: GetTicketsByAssignee :many
SELECT id, created_by, assigned_to, title, description, state, priority, created_at, updated_at, ticket_number, skills FROM tickets
WHERE assigned_to @> $1::uuid[]
ORDER BY created_at DESC
`

func (q *Queries) GetTicketsByAssignee(ctx context.Context, dollar_1 []uuid.UUID) ([]Ticket, error) {
	rows, err := q.db.QueryContext(ctx, getTicketsByAssignee, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.CreatedBy,
			pq.Array(&i.AssignedTo),
			&i.Title,
			&i.Description,
			&i.State,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TicketNumber,
			pq.Array(&i.Skills),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTicketsByCreator = `-- name: GetTicketsByCreator :many
SELECT id, created_by, assigned_to, title, description, state, priority, created_at, updated_at, ticket_number, skills FROM tickets
WHERE created_by = $1
ORDER BY created_at DESC
`

func (q *Queries) GetTicketsByCreator(ctx context.Context, createdBy uuid.UUID) ([]Ticket, error) {
	rows, err := q.db.QueryContext(ctx, getTicketsByCreator, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.CreatedBy,
			pq.Array(&i.AssignedTo),
			&i.Title,
			&i.Description,
			&i.State,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TicketNumber,
			pq.Array(&i.Skills),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllTickets = `-- name: ListAllTickets :many
SELECT id, created_by, assigned_to, title, description, state, priority, created_at, updated_at, ticket_number, skills FROM tickets
ORDER BY
  CASE WHEN $1::integer = 1 THEN ticket_number END ASC NULLS LAST,
  CASE WHEN $1::integer = 2 THEN ticket_number END DESC NULLS LAST,
  CASE WHEN $1::integer = 3 THEN created_at END ASC NULLS LAST,
  CASE WHEN $1::integer = 4 THEN created_at END DESC NULLS LAST,
  CASE WHEN $1::integer = 0 THEN id END ASC NULLS LAST
LIMIT $3 OFFSET $2
`

type ListAllTicketsParams struct {
	SortVal int32 `json:"sort_val"`
	Offset  int32 `json:"offset"`
	Limit   int32 `json:"limit"`
}

func (q *Queries) ListAllTickets(ctx context.Context, arg ListAllTicketsParams) ([]Ticket, error) {
	rows, err := q.db.QueryContext(ctx, listAllTickets, arg.SortVal, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.CreatedBy,
			pq.Array(&i.AssignedTo),
			&i.Title,
			&i.Description,
			&i.State,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TicketNumber,
			pq.Array(&i.Skills),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllTicketsByStatePriority = `-- name: ListAllTicketsByStatePriority :many
SELECT id, created_by, assigned_to, title, description, state, priority, created_at, updated_at, ticket_number, skills
FROM tickets
WHERE ($1::integer IS NULL OR state = $1::integer)
  AND ($2::integer IS NULL OR priority = $2::integer)
  AND ($3::uuid IS NULL OR created_by = $3::uuid)
  AND (
    $4::uuid IS NULL
    OR assigned_to @> ARRAY[$4::uuid]::uuid[]
  )
  AND ($5::bigint IS NULL OR ticket_number = $5::bigint)
ORDER BY
  CASE WHEN $6::integer = 1 THEN ticket_number END ASC NULLS LAST,
  CASE WHEN $6::integer = 2 THEN ticket_number END DESC NULLS LAST,
  CASE WHEN $6::integer = 3 THEN created_at END ASC NULLS LAST,
  CASE WHEN $6::integer = 4 THEN created_at END DESC NULLS LAST,
  CASE WHEN $6::integer = 0 THEN id END ASC NULLS LAST
LIMIT $8 OFFSET $7
`

type ListAllTicketsByStatePriorityParams struct {
	FilterState        sql.NullInt32 `json:"filter_state"`
	FilterPriority     sql.NullInt32 `json:"filter_priority"`
	FilterCreatedBy    uuid.NullUUID `json:"filter_created_by"`
	FilterAssignee     uuid.NullUUID `json:"filter_assignee"`
	FilterTicketNumber sql.NullInt64 `json:"filter_ticket_number"`
	SortVal            int32         `json:"sort_val"`
	OffsetVal          int32         `json:"offset_val"`
	LimitVal           int32         `json:"limit_val"`
}

// Optional filters: pass NULL for any sqlc.narg to skip that condition.
// filter_assignee: tickets where assigned_to contains this user id.
func (q *Queries) ListAllTicketsByStatePriority(ctx context.Context, arg ListAllTicketsByStatePriorityParams) ([]Ticket, error) {
	rows, err := q.db.QueryContext(ctx, listAllTicketsByStatePriority,
		arg.FilterState,
		arg.FilterPriority,
		arg.FilterCreatedBy,
		arg.FilterAssignee,
		arg.FilterTicketNumber,
		arg.SortVal,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.CreatedBy,
			pq.Array(&i.AssignedTo),
			&i.Title,
			&i.Description,
			&i.State,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TicketNumber,
			pq.Array(&i.Skills),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTickets = `-- name: ListTickets :many
SELECT id, created_by, assigned_to, title, description, state, priority, created_at, updated_at, ticket_number, skills FROM tickets WHERE created_by = $1
ORDER BY
  CASE WHEN $2::integer = 1 THEN ticket_number END ASC NULLS LAST,
  CASE WHEN $2::integer = 2 THEN ticket_number END DESC NULLS LAST,
  CASE WHEN $2::integer = 3 THEN created_at END ASC NULLS LAST,
  CASE WHEN $2::integer = 4 THEN created_at END DESC NULLS LAST,
  CASE WHEN $2::integer = 0 THEN id END ASC NULLS LAST
LIMIT $4 OFFSET $3
`

type ListTicketsParams struct {
	CreatedBy uuid.UUID `json:"created_by"`
	SortVal   int32     `json:"sort_val"`
	Offset    int32     `json:"offset"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) ListTickets(ctx context.Context, arg ListTicketsParams) ([]Ticket, error) {
	rows, err := q.db.QueryContext(ctx, listTickets,
		arg.CreatedBy,
		arg.SortVal,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.CreatedBy,
			pq.Array(&i.AssignedTo),
			&i.Title,
			&i.Description,
			&i.State,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TicketNumber,
			pq.Array(&i.Skills),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsAssigned = `-- name: ListTicketsAssigned :many
SELECT id, created_by, assigned_to, title, description, state, priority, created_at, updated_at, ticket_number, skills FROM tickets WHERE assigned_to @> $1::uuid[]
ORDER BY
  CASE WHEN $2::integer = 1 THEN ticket_number END ASC NULLS LAST,
  CASE WHEN $2::integer = 2 THEN ticket_number END DESC NULLS LAST,
  CASE WHEN $2::integer = 3 THEN created_at END ASC NULLS LAST,
  CASE WHEN $2::integer = 4 THEN created_at END DESC NULLS LAST,
  CASE WHEN $2::integer = 0 THEN id END ASC NULLS LAST
LIMIT $4 OFFSET $3
`

type ListTicketsAssignedParams struct {
	AssigneeIds []uuid.UUID `json:"assignee_ids"`
	SortVal     int32       `json:"sort_val"`
	Offset      int32       `json:"offset"`
	Limit       int32       `json:"limit"`
}

func (q *Queries) ListTicketsAssigned(ctx context.Context, arg ListTicketsAssignedParams) ([]Ticket, error) {
	rows, err := q.db.QueryContext(ctx, listTicketsAssigned,
		pq.Array(arg.AssigneeIds),
		arg.SortVal,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.CreatedBy,
			pq.Array(&i.AssignedTo),
			&i.Title,
			&i.Description,
			&i.State,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TicketNumber,
			pq.Array(&i.Skills),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTicket = `-- name: UpdateTicket :one
UPDATE tickets
SET
    title = $2,
    description = $3,
    state = $4,
    priority = $5,
    assigned_to = $6,
    updated_at = $7,
    skills = $8
WHERE id = $1
RETURNING id, created_by, assigned_to, title, description, state, priority, created_at, updated_at, ticket_number, skills
`

type UpdateTicketParams struct {
	ID          uuid.UUID   `json:"id"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	State       int32       `json:"state"`
	Priority    int32       `json:"priority"`
	AssignedTo  []uuid.UUID `json:"assigned_to"`
	UpdatedAt   time.Time   `json:"updated_at"`
	Skills      []string    `json:"skills"`
}

func (q *Queries) UpdateTicket(ctx context.Context, arg UpdateTicketParams) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, updateTicket,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.State,
		arg.Priority,
		pq.Array(arg.AssignedTo),
		arg.UpdatedAt,
		pq.Array(arg.Skills),
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		pq.Array(&i.AssignedTo),
		&i.Title,
		&i.Description,
		&i.State,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TicketNumber,
		pq.Array(&i.Skills),
	)
	return i, err
}
