// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    hashed_password,
    first_name,
    last_name,
    email,
    updated_at,
    skills
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, hashed_password, first_name, last_name, email, role, updated_at, created_at, skills, keycloak_id
`

type CreateUserParams struct {
	HashedPassword string    `json:"hashed_password"`
	FirstName      string    `json:"first_name"`
	LastName       string    `json:"last_name"`
	Email          string    `json:"email"`
	UpdatedAt      time.Time `json:"updated_at"`
	Skills         []string  `json:"skills"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.HashedPassword,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.UpdatedAt,
		pq.Array(arg.Skills),
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.HashedPassword,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Role,
		&i.UpdatedAt,
		&i.CreatedAt,
		pq.Array(&i.Skills),
		&i.KeycloakID,
	)
	return i, err
}

const createUserFromKeycloak = `-- name: CreateUserFromKeycloak :one
INSERT INTO users (
    keycloak_id,
    first_name,
    last_name,
    email,
    role,
    hashed_password,
    skills,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, '!external', '{}', NOW()
) RETURNING id, hashed_password, first_name, last_name, email, role, updated_at, created_at, skills, keycloak_id
`

type CreateUserFromKeycloakParams struct {
	KeycloakID uuid.NullUUID  `json:"keycloak_id"`
	FirstName  string         `json:"first_name"`
	LastName   string         `json:"last_name"`
	Email      string         `json:"email"`
	Role       sql.NullString `json:"role"`
}

// JIT provisioning: first sign-in of a Keycloak subject with no local row.
func (q *Queries) CreateUserFromKeycloak(ctx context.Context, arg CreateUserFromKeycloakParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUserFromKeycloak,
		arg.KeycloakID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.HashedPassword,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Role,
		&i.UpdatedAt,
		&i.CreatedAt,
		pq.Array(&i.Skills),
		&i.KeycloakID,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getAllAgents = `-- name: GetAllAgents :many
SELECT id, hashed_password, first_name, last_name, email, role, updated_at, created_at, skills, keycloak_id FROM users
WHERE role = 'agent'
ORDER BY created_at
`

func (q *Queries) GetAllAgents(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAllAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.HashedPassword,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Role,
			&i.UpdatedAt,
			&i.CreatedAt,
			pq.Array(&i.Skills),
			&i.KeycloakID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, first_name, last_name, email FROM users
ORDER BY created_at DESC
`

type GetAllUsersRow struct {
	ID        uuid.UUID `json:"id"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	Email     string    `json:"email"`
}

func (q *Queries) GetAllUsers(ctx context.Context) ([]GetAllUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllUsersRow{}
	for rows.Next() {
		var i GetAllUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAutoAssignmentCandidates = `-- name: GetAutoAssignmentCandidates :many
WITH active_workload AS (
    SELECT
        assignee_id,
        COUNT(*)::int4 AS active_ticket_count
    FROM tickets
    CROSS JOIN LATERAL unnest(COALESCE(assigned_to, ARRAY[]::uuid[])) AS assignee_id
    WHERE state = ANY($2::int[])
    GROUP BY assignee_id
)
SELECT
    users.id,
    users.hashed_password,
    users.first_name,
    users.last_name,
    users.email,
    users.role,
    users.updated_at,
    users.created_at,
    users.skills,
    COALESCE(active_workload.active_ticket_count, 0)::int4 AS active_ticket_count
FROM users
LEFT JOIN active_workload ON active_workload.assignee_id = users.id
WHERE users.role = 'agent'
  AND users.skills && $1::text[]
ORDER BY active_ticket_count ASC, users.created_at ASC
`

type GetAutoAssignmentCandidatesParams struct {
	RequiredSkills []string `json:"required_skills"`
	ActiveStates   []int32  `json:"active_states"`
}

type GetAutoAssignmentCandidatesRow struct {
	ID                uuid.UUID      `json:"id"`
	HashedPassword    string         `json:"hashed_password"`
	FirstName         string         `json:"first_name"`
	LastName          string         `json:"last_name"`
	Email             string         `json:"email"`
	Role              sql.NullString `json:"role"`
	UpdatedAt         time.Time      `json:"updated_at"`
	CreatedAt         time.Time      `json:"created_at"`
	Skills            []string       `json:"skills"`
	ActiveTicketCount int32          `json:"active_ticket_count"`
}

func (q *Queries) GetAutoAssignmentCandidates(ctx context.Context, arg GetAutoAssignmentCandidatesParams) ([]GetAutoAssignmentCandidatesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAutoAssignmentCandidates, pq.Array(arg.RequiredSkills), pq.Array(arg.ActiveStates))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAutoAssignmentCandidatesRow{}
	for rows.Next() {
		var i GetAutoAssignmentCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.HashedPassword,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Role,
			&i.UpdatedAt,
			&i.CreatedAt,
			pq.Array(&i.Skills),
			&i.ActiveTicketCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT id, hashed_password, first_name, last_name, email, role, updated_at, created_at, skills, keycloak_id FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.HashedPassword,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Role,
		&i.UpdatedAt,
		&i.CreatedAt,
		pq.Array(&i.Skills),
		&i.KeycloakID,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, hashed_password, first_name, last_name, email, role, updated_at, created_at, skills, keycloak_id FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.HashedPassword,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Role,
		&i.UpdatedAt,
		&i.CreatedAt,
		pq.Array(&i.Skills),
		&i.KeycloakID,
	)
	return i, err
}

const getUserByKeycloakID = `-- name: GetUserByKeycloakID :one
SELECT id, hashed_password, first_name, last_name, email, role, updated_at, created_at, skills, keycloak_id FROM users
WHERE keycloak_id = $1 LIMIT 1
`

func (q *Queries) GetUserByKeycloakID(ctx context.Context, keycloakID uuid.NullUUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByKeycloakID, keycloakID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.HashedPassword,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Role,
		&i.UpdatedAt,
		&i.CreatedAt,
		pq.Array(&i.Skills),
		&i.KeycloakID,
	)
	return i, err
}

const getUsersByIDs = `-- name: GetUsersByIDs :many
SELECT id, hashed_password, first_name, last_name, email, role, updated_at, created_at, skills, keycloak_id FROM users
WHERE id = ANY($1::uuid[])
`

func (q *Queries) GetUsersByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUsersByIDs, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.HashedPassword,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Role,
			&i.UpdatedAt,
			&i.CreatedAt,
			pq.Array(&i.Skills),
			&i.KeycloakID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkUserToKeycloak = `-- name: LinkUserToKeycloak :one
UPDATE users
SET keycloak_id = $2, first_name = $3, last_name = $4, role = $5, updated_at = NOW()
WHERE id = $1 AND keycloak_id IS NULL
RETURNING id, hashed_password, first_name, last_name, email, role, updated_at, created_at, skills, keycloak_id
`

type LinkUserToKeycloakParams struct {
	ID         uuid.UUID      `json:"id"`
	KeycloakID uuid.NullUUID  `json:"keycloak_id"`
	FirstName  string         `json:"first_name"`
	LastName   string         `json:"last_name"`
	Role       sql.NullString `json:"role"`
}

// Claims a pre-existing row (matched by email) for a Keycloak subject, and
// refreshes the profile/role from the token. The keycloak_id IS NULL guard makes
// this a no-op if the row was already linked to a different subject, so a second
// Keycloak account with the same email can never steal an existing identity.
func (q *Queries) LinkUserToKeycloak(ctx context.Context, arg LinkUserToKeycloakParams) (User, error) {
	row := q.db.QueryRowContext(ctx, linkUserToKeycloak,
		arg.ID,
		arg.KeycloakID,
		arg.FirstName,
		arg.LastName,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.HashedPassword,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Role,
		&i.UpdatedAt,
		&i.CreatedAt,
		pq.Array(&i.Skills),
		&i.KeycloakID,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, hashed_password, first_name, last_name, email, role, updated_at, created_at, skills, keycloak_id FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.HashedPassword,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Role,
			&i.UpdatedAt,
			&i.CreatedAt,
			pq.Array(&i.Skills),
			&i.KeycloakID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncUserFromKeycloak = `-- name: SyncUserFromKeycloak :one
UPDATE users
SET email = $2, first_name = $3, last_name = $4, role = $5, updated_at = NOW()
WHERE keycloak_id = $1
RETURNING id, hashed_password, first_name, last_name, email, role, updated_at, created_at, skills, keycloak_id
`

type SyncUserFromKeycloakParams struct {
	KeycloakID uuid.NullUUID  `json:"keycloak_id"`
	Email      string         `json:"email"`
	FirstName  string         `json:"first_name"`
	LastName   string         `json:"last_name"`
	Role       sql.NullString `json:"role"`
}

// Refreshes a linked row when the token's profile or role has drifted from it.
func (q *Queries) SyncUserFromKeycloak(ctx context.Context, arg SyncUserFromKeycloakParams) (User, error) {
	row := q.db.QueryRowContext(ctx, syncUserFromKeycloak,
		arg.KeycloakID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.HashedPassword,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Role,
		&i.UpdatedAt,
		&i.CreatedAt,
		pq.Array(&i.Skills),
		&i.KeycloakID,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET email = $2, first_name = $3, last_name = $4, role = $5, updated_at = $6, skills = $7
WHERE id = $1
RETURNING id, hashed_password, first_name, last_name, email, role, updated_at, created_at, skills, keycloak_id
`

type UpdateUserParams struct {
	ID        uuid.UUID      `json:"id"`
	Email     string         `json:"email"`
	FirstName string         `json:"first_name"`
	LastName  string         `json:"last_name"`
	Role      sql.NullString `json:"role"`
	UpdatedAt time.Time      `json:"updated_at"`
	Skills    []string       `json:"skills"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.Role,
		arg.UpdatedAt,
		pq.Array(arg.Skills),
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.HashedPassword,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Role,
		&i.UpdatedAt,
		&i.CreatedAt,
		pq.Array(&i.Skills),
		&i.KeycloakID,
	)
	return i, err
}
