from __future__ import annotations

import json
import shutil
import subprocess
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
CONTRACT_PATH = ROOT / "contracts" / "ticket_state_machine.json"

GO_OUT = ROOT / "apps" / "ticket-service" / "internal" / "domain" / "ticket_state_contract_gen.go"
PY_OUT = ROOT / "apps" / "ai-service" / "app" / "generated" / "ticket_state_contract.py"
TS_OUT = ROOT / "apps" / "web" / "src" / "lib" / "ticket-state-contract.generated.ts"


def load_states() -> list[dict[str, Any]]:
    payload = json.loads(CONTRACT_PATH.read_text())
    states = payload["states"]
    keys = {state["key"] for state in states}
    for state in states:
        unknown = set(state["transitions"]) - keys
        if unknown:
            raise ValueError(f"{state['key']} has unknown transitions: {sorted(unknown)}")
    return states


def go_list(values: list[str]) -> str:
    return ", ".join(values)


def write_go(states: list[dict[str, Any]]) -> None:
    const_lines = "\n".join(
        f"\t{state['goConst']} TicketState = {state['numericValue']}" for state in states
    )
    wire_lines = "\n".join(
        f'\t{state["goConst"]}: "{state["wire"]}",' for state in states
    )
    alias_lines = []
    for state in states:
        for alias in state["aliases"]:
            alias_lines.append(f'\t"{alias}": {state["goConst"]},')
    transition_lines = []
    for state in states:
        targets = [next(s["goConst"] for s in states if s["key"] == key) for key in state["transitions"]]
        transition_lines.append(f"\t{state['goConst']}: {{{go_list(targets)}}},")
    order_values = go_list([state["goConst"] for state in states])

    GO_OUT.write_text(
        f"""// Code generated by tools/generate_ticket_state_contract.py; DO NOT EDIT.

package domain

const (
{const_lines}
)

var ticketStateWireValues = map[TicketState]string{{
{wire_lines}
}}

var ticketStateByInput = map[string]TicketState{{
{chr(10).join(alias_lines)}
}}

var allowedTransitions = map[TicketState][]TicketState{{
{chr(10).join(transition_lines)}
}}

var ticketStateOrder = []TicketState{{{order_values}}}
""",
    )
    # gofmt so the checked-in file matches CI regeneration byte-for-byte (the
    # raw template is column-unaligned; gofmt is deterministic).
    gofmt = shutil.which("gofmt")
    if gofmt:
        subprocess.run([gofmt, "-w", str(GO_OUT)], check=True)


def py_dict(items: dict[str, Any]) -> str:
    return json.dumps(items, indent=4)


def write_python(states: list[dict[str, Any]]) -> None:
    PY_OUT.parent.mkdir(parents=True, exist_ok=True)
    enum_members = {state["pythonMember"]: state["wire"] for state in states}
    aliases = {
        alias.replace(" ", "_"): state["wire"]
        for state in states
        for alias in state["aliases"]
    }
    aliases.update({alias: state["wire"] for state in states for alias in state["aliases"]})
    transitions = {state["wire"]: state["transitions"] for state in states}

    PY_OUT.write_text(
        f'''# Code generated by tools/generate_ticket_state_contract.py; DO NOT EDIT.
from __future__ import annotations

TICKET_STATE_ENUM_MEMBERS = {py_dict(enum_members)}

TICKET_STATE_ALIASES = {py_dict(aliases)}

ALLOWED_TRANSITION_VALUES = {py_dict(transitions)}
''',
    )


def ts_const(name: str, value: Any) -> str:
    return f"export const {name} = {json.dumps(value, indent=4)} as const;"


def write_typescript(states: list[dict[str, Any]]) -> None:
    order = [state["wire"] for state in states]
    transitions = {state["wire"]: state["transitions"] for state in states}
    labels = {state["wire"]: state["label"] for state in states}
    action_labels = {state["wire"]: state["actionLabel"] for state in states}
    aliases = {
        alias: state["wire"]
        for state in states
        for alias in state["aliases"]
    }
    number_to_wire = {str(state["numericValue"]): state["wire"] for state in states}

    TS_OUT.write_text(
        "\n".join(
            [
                "// Code generated by tools/generate_ticket_state_contract.py; DO NOT EDIT.",
                "",
                ts_const("TICKET_STATE_ORDER", order),
                "",
                "export type ApiTicketState = (typeof TICKET_STATE_ORDER)[number];",
                "",
                ts_const("TICKET_STATE_TRANSITIONS", transitions),
                "",
                ts_const("TICKET_STATE_LABELS", labels),
                "",
                ts_const("TICKET_STATE_ACTION_LABELS", action_labels),
                "",
                ts_const("TICKET_STATE_ALIASES", aliases),
                "",
                ts_const("TICKET_STATE_NUMBER_TO_WIRE", number_to_wire),
                "",
            ]
        )
    )


def main() -> None:
    states = load_states()
    write_go(states)
    write_python(states)
    write_typescript(states)


if __name__ == "__main__":
    main()
