// Code generated by tools/generate_ticket_state_contract.py; DO NOT EDIT.

export const TICKET_STATE_ORDER = [
    "open",
    "pending",
    "in_progress",
    "resolved",
    "closed",
    "cancelled"
] as const;

export type ApiTicketState = (typeof TICKET_STATE_ORDER)[number];

export const TICKET_STATE_TRANSITIONS = {
    "open": [
        "pending",
        "in_progress",
        "cancelled"
    ],
    "pending": [
        "open",
        "in_progress",
        "resolved",
        "cancelled"
    ],
    "in_progress": [
        "resolved"
    ],
    "resolved": [
        "open",
        "pending",
        "closed",
        "cancelled"
    ],
    "closed": [],
    "cancelled": []
} as const;

export const TICKET_STATE_LABELS = {
    "open": "Open",
    "pending": "Pending",
    "in_progress": "In progress",
    "resolved": "Resolved",
    "closed": "Closed",
    "cancelled": "Cancelled"
} as const;

export const TICKET_STATE_ACTION_LABELS = {
    "open": "Reopen",
    "pending": "Mark pending",
    "in_progress": "Start work",
    "resolved": "Resolve ticket",
    "closed": "Close ticket",
    "cancelled": "Cancel ticket"
} as const;

export const TICKET_STATE_ALIASES = {
    "open": "open",
    "pending": "pending",
    "in_progress": "in_progress",
    "in progress": "in_progress",
    "resolved": "resolved",
    "closed": "closed",
    "cancelled": "cancelled",
    "cancel": "cancelled"
} as const;

export const TICKET_STATE_NUMBER_TO_WIRE = {
    "1": "open",
    "2": "pending",
    "3": "in_progress",
    "4": "resolved",
    "5": "closed",
    "6": "cancelled"
} as const;
